### PR TITLE
Add user error message for smt/enable|next-theme|set-theme when SVG not available

### PR DESCRIPTION
**Pull request by jasonm23**

### CODE REVIEW

**Comment by sabof** [comment]
Perhaps use something like `(display-warning 'svg-mode-line-themes "SVG support is not available")` followed by return in `smt/enable`? An error may potentially halt the loading of an init file, which seems undesirable. 

I'm also not sure that adding checks in something other than `smt/enable` is necessary.

**Comment by jasonm23** [comment]
Seems fair, I thought `user-error` didn't halt anything other than the current defun, but `return-from` sounds safer with a warning.

**Comment by jasonm23** [comment]
updated, take a look.

**Comment by sabof** [comment]
Merged

**Pull request closed without merging**
